// {
//     status: 'success',
//     locale: 'tr',
//     systemTime: 1667999705093,
//     conversationId: '123456789',
//     price: 1,
//     paidPrice: 1.2,
//     installment: 1,
//     paymentId: '18471515',
//     fraudStatus: 1,
//     merchantCommissionRate: 20,
//     merchantCommissionRateAmount: 0.2,
//     iyziCommissionRateAmount: 0.048,
//     iyziCommissionFee: 0.25,
//     cardType: 'CREDIT_CARD',
//     cardAssociation: 'MASTER_CARD',
//     cardFamily: 'Paraf',
//     binNumber: '552879',
//     lastFourDigits: '0008',
//     basketId: 'B67832',
//     currency: 'TRY',
//     itemTransactions: [
//       {
//         itemId: 'BI101',
//         paymentTransactionId: '19687125',
//         transactionStatus: 2,
//         price: 0.3,
//         paidPrice: 0.36,
//         merchantCommissionRate: 20,
//         merchantCommissionRateAmount: 0.06,
//         iyziCommissionRateAmount: 0.0144,
//         iyziCommissionFee: 0.075,
//         blockageRate: 0,
//         blockageRateAmountMerchant: 0,
//         blockageRateAmountSubMerchant: 0,
//         blockageResolvedDate: '2022-11-17 00:00:00',
//         subMerchantPrice: 0,
//         subMerchantPayoutRate: 0,
//         subMerchantPayoutAmount: 0,
//         merchantPayoutAmount: 0.2706,
//         convertedPayout: [Object]
//       },
//       {
//         itemId: 'BI102',
//         paymentTransactionId: '19687126',
//         transactionStatus: 2,
//         price: 0.5,
//         paidPrice: 0.6,
//         merchantCommissionRate: 20,
//         merchantCommissionRateAmount: 0.1,
//         iyziCommissionRateAmount: 0.024,
//         iyziCommissionFee: 0.125,
//         blockageRate: 0,
//         blockageRateAmountMerchant: 0,
//         blockageRateAmountSubMerchant: 0,
//         blockageResolvedDate: '2022-11-17 00:00:00',
//         subMerchantPrice: 0,
//         subMerchantPayoutRate: 0,
//         subMerchantPayoutAmount: 0,
//         merchantPayoutAmount: 0.451,
//         convertedPayout: [Object]
//       },
//       {
//         itemId: 'BI103',
//         paymentTransactionId: '19687127',
//         transactionStatus: 2,
//         price: 0.2,
//         paidPrice: 0.24,
//         merchantCommissionRate: 20,
//         merchantCommissionRateAmount: 0.04,
//         iyziCommissionRateAmount: 0.0096,
//         iyziCommissionFee: 0.05,
//         blockageRate: 0,
//         blockageRateAmountMerchant: 0,
//         blockageRateAmountSubMerchant: 0,
//         blockageResolvedDate: '2022-11-17 00:00:00',
//         subMerchantPrice: 0,
//         subMerchantPayoutRate: 0,
//         subMerchantPayoutAmount: 0,
//         merchantPayoutAmount: 0.1804,
//         convertedPayout: [Object]
//       }
//     ],
//     authCode: '618274',
//     phase: 'AUTH',
//     hostReference: 'mock00001iyzihostrfn'
//   } 1 id'li kullanıcı için kartını si
//   [nodemon] clean exit - waiting for changes before restart
//   [nodemon] restarting due to changes...
//   [nodemon] starting `node -r esm services/iyzipay/index.js`
//   {
//     status: 'success',
//     locale: 'tr',
//     systemTime: 1667999777684,
//     conversationId: '123456789',
//     price: 1,
//     paidPrice: 1.2,
//     installment: 1,
//     paymentId: '18471524',
//     fraudStatus: 1,
//     merchantCommissionRate: 20,
//     merchantCommissionRateAmount: 0.2,
//     iyziCommissionRateAmount: 0.048,
//     iyziCommissionFee: 0.25,
//     cardType: 'CREDIT_CARD',
//     cardAssociation: 'MASTER_CARD',
//     cardFamily: 'Paraf',
//     binNumber: '552879',
//     lastFourDigits: '0008',
//     basketId: 'B67832',
//     currency: 'TRY',
//     itemTransactions: [
//       {
//         itemId: 'BI101',
//         paymentTransactionId: '19687133',
//         transactionStatus: 2,
//         price: 0.3,
//         paidPrice: 0.36,
//         merchantCommissionRate: 20,
//         merchantCommissionRateAmount: 0.06,
//         iyziCommissionRateAmount: 0.0144,
//         iyziCommissionFee: 0.075,
//         blockageRate: 0,
//         blockageRateAmountMerchant: 0,
//         blockageRateAmountSubMerchant: 0,
//         blockageResolvedDate: '2022-11-17 00:00:00',
//         subMerchantPrice: 0,
//         subMerchantPayoutRate: 0,
//         subMerchantPayoutAmount: 0,
//         merchantPayoutAmount: 0.2706,
//         convertedPayout: [Object]
//       },
//       {
//         itemId: 'BI102',
//         paymentTransactionId: '19687140',
//         transactionStatus: 2,
//         price: 0.5,
//         paidPrice: 0.6,
//         merchantCommissionRate: 20,
//         merchantCommissionRateAmount: 0.1,
//         iyziCommissionRateAmount: 0.024,
//         iyziCommissionFee: 0.125,
//         blockageRate: 0,
//         blockageRateAmountMerchant: 0,
//         blockageRateAmountSubMerchant: 0,
//         blockageResolvedDate: '2022-11-17 00:00:00',
//         subMerchantPrice: 0,
//         subMerchantPayoutRate: 0,
//         subMerchantPayoutAmount: 0,
//         merchantPayoutAmount: 0.451,
//         convertedPayout: [Object]
//       },
//       {
//         itemId: 'BI103',
//         paymentTransactionId: '19687141',
//         transactionStatus: 2,
//         price: 0.2,
//         paidPrice: 0.24,
//         merchantCommissionRate: 20,
//         merchantCommissionRateAmount: 0.04,
//         iyziCommissionRateAmount: 0.0096,
//         iyziCommissionFee: 0.05,
//         blockageRate: 0,
//         blockageRateAmountMerchant: 0,
//         blockageRateAmountSubMerchant: 0,
//         blockageResolvedDate: '2022-11-17 00:00:00',
//         subMerchantPrice: 0,
//         subMerchantPayoutRate: 0,
//         subMerchantPayoutAmount: 0,
//         merchantPayoutAmount: 0.1804,
//         convertedPayout: [Object]
//       }
//     ],
//     authCode: '558543',
//     phase: 'AUTH',
//     hostReference: 'mock00001iyzihostrfn'
//   } 1 id'li kullanıcı için kartını si
//   [nodemon] clean exit - waiting for changes before restart
//   [nodemon] restarting due to changes...
//   [nodemon] starting `node -r esm services/iyzipay/index.js`
//   {
//     status: 'success',
//     locale: 'tr',
//     systemTime: 1667999781852,
//     conversationId: '123456789',
//     price: 1,
//     paidPrice: 1.2,
//     installment: 1,
//     paymentId: '18471521',
//     fraudStatus: 1,
//     merchantCommissionRate: 20,
//     merchantCommissionRateAmount: 0.2,
//     iyziCommissionRateAmount: 0.048,
//     iyziCommissionFee: 0.25,
//     cardType: 'CREDIT_CARD',
//     cardAssociation: 'MASTER_CARD',
//     cardFamily: 'Paraf',
//     binNumber: '552879',
//     lastFourDigits: '0008',
//     basketId: 'B67832',
//     currency: 'TRY',
//     itemTransactions: [
//       {
//         itemId: 'BI101',
//         paymentTransactionId: '19687138',
//         transactionStatus: 2,
//         price: 0.3,
//         paidPrice: 0.36,
//         merchantCommissionRate: 20,
//         merchantCommissionRateAmount: 0.06,
//         iyziCommissionRateAmount: 0.0144,
//         iyziCommissionFee: 0.075,
//         blockageRate: 0,
//         blockageRateAmountMerchant: 0,
//         blockageRateAmountSubMerchant: 0,
//         blockageResolvedDate: '2022-11-17 00:00:00',
//         subMerchantPrice: 0,
//         subMerchantPayoutRate: 0,
//         subMerchantPayoutAmount: 0,
//         merchantPayoutAmount: 0.2706,
//         convertedPayout: [Object]
//       },
//       {
//         itemId: 'BI102',
//         paymentTransactionId: '19687139',
//         transactionStatus: 2,
//         price: 0.5,
//         paidPrice: 0.6,
//         merchantCommissionRate: 20,
//         merchantCommissionRateAmount: 0.1,
//         iyziCommissionRateAmount: 0.024,
//         iyziCommissionFee: 0.125,
//         blockageRate: 0,
//         blockageRateAmountMerchant: 0,
//         blockageRateAmountSubMerchant: 0,
//         blockageResolvedDate: '2022-11-17 00:00:00',
//         subMerchantPrice: 0,
//         subMerchantPayoutRate: 0,
//         subMerchantPayoutAmount: 0,
//         merchantPayoutAmount: 0.451,
//         convertedPayout: [Object]
//       },
//       {
//         itemId: 'BI103',
//         paymentTransactionId: '19687143',
//         transactionStatus: 2,
//         price: 0.2,
//         paidPrice: 0.24,
//         merchantCommissionRate: 20,
//         merchantCommissionRateAmount: 0.04,
//         iyziCommissionRateAmount: 0.0096,
//         iyziCommissionFee: 0.05,
//         blockageRate: 0,
//         blockageRateAmountMerchant: 0,
//         blockageRateAmountSubMerchant: 0,
//         blockageResolvedDate: '2022-11-17 00:00:00',
//         subMerchantPrice: 0,
//         subMerchantPayoutRate: 0,
//         subMerchantPayoutAmount: 0,
//         merchantPayoutAmount: 0.1804,
//         convertedPayout: [Object]
//       }
//     ],
//     authCode: '820766',
//     phase: 'AUTH',
//     hostReference: 'mock00001iyzihostrfn'
//   }



// 



// {
//   status: 'success',
//   locale: 'tr',
//   systemTime: 1667999997799,
//   conversationId: '7oEohsxUZJR4yVvDb8vJS',
//   externalId: 'LrffrLRa66i9oV8QZ7QBw',
//   email: 'email@email.com',
//   cardUserKey: 'rfW/0dXc9hNtybaHbpETyL0jiF4=',
//   cardToken: 'J0wyYMYmy9zTr+w1vu/TVANn77s=',
//   cardAlias: 'Saklı karta verilen isim',
//   binNumber: '55287900',
//   lastFourDigits: '0008',
//   cardType: 'CREDIT_CARD',
//   cardAssociation: 'MASTER_CARD',
//   cardFamily: 'Paraf',
//   cardBankCode: 12,
//   cardBankName: 'Halk Bankası'
// } 1 id'li kullanıcı için kart oluştur